# Generated by Django 4.1.2 on 2022-10-15 20:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="say something about yourself", verbose_name="About Me"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+306900000000",
                max_length=128,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
