# Generated by Django 4.1.2 on 2022-10-18 18:47

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Article Title"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Article Reference Code",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Default description...update me please....",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="GR", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "article_number",
                    models.IntegerField(
                        default=112,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Article Number",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Price",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.24,
                        help_text="24% article tax charged",
                        max_digits=6,
                        verbose_name="Article Tax",
                    ),
                ),
                (
                    "words",
                    models.IntegerField(default=0, verbose_name="Number of Words"),
                ),
                (
                    "total_words",
                    models.IntegerField(
                        default=0, verbose_name="Total Number of Words"
                    ),
                ),
                (
                    "paragraphs",
                    models.IntegerField(default=0, verbose_name="Paragraphs"),
                ),
                ("subtitles", models.IntegerField(default=0, verbose_name="Subtitles")),
                (
                    "keywords",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "advert_type",
                    models.CharField(
                        choices=[
                            ("For Sale", "For Sale"),
                            ("For Read", "For Read"),
                            ("Auction", "Auction"),
                        ],
                        default="For Sale",
                        max_length=50,
                        verbose_name="Advert Type",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("Book Review", "Book Review"),
                            ("Short Report", "Short Report"),
                            ("Software Article", "Software Article"),
                            ("News Article", "News Article"),
                            ("Research Article", "Research Article"),
                            ("Review Article", "Review Article"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                        verbose_name="Article Type",
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        default="/article_sample.png",
                        null=True,
                        upload_to="",
                        verbose_name="Article Cover",
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True,
                        default="/interior_sample.png",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        default="/interior_sample.png",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True,
                        default="/interior_sample.png",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True,
                        default="/interior_sample.png",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "published_status",
                    models.BooleanField(default=False, verbose_name="Published Status"),
                ),
                (
                    "views",
                    models.ImageField(
                        default=0, upload_to="", verbose_name="Total Views"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="author_buyer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author, Seller or Buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.CreateModel(
            name="ArticleViews",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(max_length=250, verbose_name="IP Address")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_views",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Views on Article",
                "verbose_name_plural": "Total Articles Views",
            },
        ),
    ]
