# Generated by Django 4.1.2 on 2022-10-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Total Views"),
        ),
    ]
